#SQL Connection
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/userdb
    name: user_reg
    username: root
    password: ENC(50sp6H9n/6nEhb0NxVXHCe593KfrmSok)
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
---
#Password Encryption
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: projectPassword
---
#Server
server:
  error:
    whitelabel:
      enabled: false
---
#Spring Kafka
spring:
  kafka:
    template:
      default-topic: userdata-topic
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
